<?php
/**
 * CSSTidy - CSS Parser and Optimiser
 *
 * CSS Printing class
 * This class prints CSS data generated by csstidy.
 *
 * Copyright 2005, 2006, 2007 Florian Schmitz
 *
 * This file is part of CSSTidy.
 *
 *   CSSTidy is free software; you can redistribute it and/or modify
 *   it under the terms of the GNU Lesser General Public License as published by
 *   the Free Software Foundation; either version 2.1 of the License, or
 *   (at your option) any later version.
 *
 *   CSSTidy is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *   GNU Lesser General Public License for more details.
 *
 *   You should have received a copy of the GNU Lesser General Public License
 *   along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 * @license http://opensource.org/licenses/lgpl-license.php GNU Lesser General Public License
 * @package csstidy
 * @author Jakub Onderka (acci at acci dot cz) 2011
 */
namespace CSSTidy;

class Logger
{
    const MESSAGE = 'm',
        TYPE = 't';

    // Constants for log type
    const ERROR = 'Error',
        WARNING = 'Warning',
        INFORMATION = 'Information';

    /** @var array */
    protected $log = array();

    /** @var int */
    protected $line = 1;

    /**
     * Add a message to the message log
     * @param string $message
     * @param string $type
     * @param integer $line
     * @version 1.0
     */
    public function log($message, $type, $line = -1)
    {
        if ($line === -1) {
            $line = $this->line;
        }

        $line = (int) $line;

        $add = array(self::MESSAGE => $message, self::TYPE => $type);
        if (!isset($this->log[$line]) || !in_array($add, $this->log[$line])) {
            $this->log[$line][] = $add;
        }
    }

    /**
     * @return int
     */
    public function incrementLine()
    {
        return ++$this->line;
    }

    /**
     * @return array
     */
    public function getMessages()
    {
        return $this->log;
    }
}