<?php

/**
 * CSSTidy - CSS Parser and Optimiser
 *
 * CSS Optimising Class
 * This class optimises CSS data generated by csstidy.
 *
 * Copyright 2005, 2006, 2007 Florian Schmitz
 *
 * This file is part of CSSTidy.
 *
 *   CSSTidy is free software; you can redistribute it and/or modify
 *   it under the terms of the GNU Lesser General Public License as published by
 *   the Free Software Foundation; either version 2.1 of the License, or
 *   (at your option) any later version.
 *
 *   CSSTidy is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *   GNU Lesser General Public License for more details.
 * 
 *   You should have received a copy of the GNU Lesser General Public License
 *   along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 * @license http://opensource.org/licenses/lgpl-license.php GNU Lesser General Public License
 * @package csstidy
 * @author Florian Schmitz (floele at gmail dot com) 2005-2007
 * @author Brett Zamir (brettz9 at yahoo dot com) 2007
 * @author Nikolay Matsievsky (speed at webo dot name) 2009-2010
 * @author Jakub Onderka (acci at acci dot cz) 2011
 */
namespace CSSTidy;
/**
 * CSS Optimising Class
 *
 * This class optimises CSS data generated by csstidy.
 *
 * @package csstidy
 * @author Florian Schmitz (floele at gmail dot com) 2005-2006
 * @version 1.0
 */
class Optimise
{
    /** @var \CSSTidy\Logger */
    protected $logger;

    /** @var \CSSTidy\Configuration */
    protected $configuration;

    /**
     * Properties that allow <color> as value
     *
     * @todo CSS3 properties
     * @see compress_numbers();
     * @static
     * @var array
     */
    public static $colorValues = array(
        'background-color' => true,
        'border-color' => true,
        'border-top-color' => true,
        'border-right-color' => true,
        'border-bottom-color' => true,
        'border-left-color' => true,
        'color' => true,
        'outline-color' => true
    );

    /**
     * All CSS units (CSS 3 units included)
     *
     * @see compress_numbers()
     * @static
     * @var array
     */
    public static $units = array('in','cm','mm','pt','pc','px','rem','em','%','ex','gd','vw','vh','vm','deg','grad','rad','ms','s','khz','hz','dpi','dpcm','dppx');

    /**
     * Properties that need a value with unit
     *
     * @todo CSS3 properties
     * @see compress_numbers();
     * @static
     * @var array
     */
    public static $unitValues = array ('background', 'background-position', 'border', 'border-top', 'border-right', 'border-bottom', 'border-left', 'border-width',
                                'border-top-width', 'border-right-width', 'border-left-width', 'border-bottom-width', 'bottom', 'border-spacing',
                                'font-size', 'height', 'left', 'margin', 'margin-top', 'margin-right', 'margin-bottom', 'margin-left', 'max-height',
                                'max-width', 'min-height', 'min-width', 'outline', 'outline-width', 'padding', 'padding-top', 'padding-right',
                                'padding-bottom', 'padding-left', 'right', 'top', 'text-indent', 'letter-spacing', 'word-spacing', 'width');

    /**
     * A list of all shorthand properties that are devided into four properties and/or have four subvalues
     *
     * @todo Are there new ones in CSS3?
     * @see dissolve_4value_shorthands()
     * @see merge_4value_shorthands()
     */
    public static $shorthands = array(
        'border-color' => array('border-top-color','border-right-color','border-bottom-color','border-left-color'),
        'border-style' => array('border-top-style','border-right-style','border-bottom-style','border-left-style'),
        'border-width' => array('border-top-width','border-right-width','border-bottom-width','border-left-width'),
        'margin' => array('margin-top','margin-right','margin-bottom','margin-left'),
        'padding' => array('padding-top','padding-right','padding-bottom','padding-left'),
        'border-radius' => array('border-radius-top-left', 'border-radius-top-right', 'border-radius-bottom-right', 'border-radius-bottom-left')
    );
    
    public static $replaceColors = array(
        'aliceblue' => '#f0f8ff',
        'antiquewhite' => '#faebd7',
        'aquamarine' => '#7fffd4',
        'azure' => '#f0ffff',
        'beige' => '#f5f5dc',
        'bisque' => '#ffe4c4',
        'blanchedalmond' => '#ffebcd',
        'blueviolet' => '#8a2be2',
        'brown' => '#a52a2a',
        'burlywood' => '#deb887',
        'cadetblue' => '#5f9ea0',
        'chartreuse' => '#7fff00',
        'chocolate' => '#d2691e',
        'coral' => '#ff7f50',
        'cornflowerblue' => '#6495ed',
        'cornsilk' => '#fff8dc',
        'crimson' => '#dc143c',
        'cyan' => '#00ffff',
        'darkblue' => '#00008b',
        'darkcyan' => '#008b8b',
        'darkgoldenrod' => '#b8860b',
        'darkgray' => '#a9a9a9',
        'darkgreen' => '#006400',
        'darkkhaki' => '#bdb76b',
        'darkmagenta' => '#8b008b',
        'darkolivegreen' => '#556b2f',
        'darkorange' => '#ff8c00',
        'darkorchid' => '#9932cc',
        'darkred' => '#8b0000',
        'darksalmon' => '#e9967a',
        'darkseagreen' => '#8fbc8f',
        'darkslateblue' => '#483d8b',
        'darkslategray' => '#2f4f4f',
        'darkturquoise' => '#00ced1',
        'darkviolet' => '#9400d3',
        'deeppink' => '#ff1493',
        'deepskyblue' => '#00bfff',
        'dimgray' => '#696969',
        'dodgerblue' => '#1e90ff',
        'feldspar' => '#d19275',
        'firebrick' => '#b22222',
        'floralwhite' => '#fffaf0',
        'forestgreen' => '#228b22',
        'gainsboro' => '#dcdcdc',
        'ghostwhite' => '#f8f8ff',
        'gold' => '#ffd700',
        'goldenrod' => '#daa520',
        'greenyellow' => '#adff2f',
        'honeydew' => '#f0fff0',
        'hotpink' => '#ff69b4',
        'indianred' => '#cd5c5c',
        'indigo' => '#4b0082',
        'ivory' => '#fffff0',
        'khaki' => '#f0e68c',
        'lavender' => '#e6e6fa',
        'lavenderblush' => '#fff0f5',
        'lawngreen' => '#7cfc00',
        'lemonchiffon' => '#fffacd',
        'lightblue' => '#add8e6',
        'lightcoral' => '#f08080',
        'lightcyan' => '#e0ffff',
        'lightgoldenrodyellow' => '#fafad2',
        'lightgrey' => '#d3d3d3',
        'lightgreen' => '#90ee90',
        'lightpink' => '#ffb6c1',
        'lightsalmon' => '#ffa07a',
        'lightseagreen' => '#20b2aa',
        'lightskyblue' => '#87cefa',
        'lightslateblue' => '#8470ff',
        'lightslategray' => '#778899',
        'lightsteelblue' => '#b0c4de',
        'lightyellow' => '#ffffe0',
        'limegreen' => '#32cd32',
        'linen' => '#faf0e6',
        'magenta' => '#ff00ff',
        'mediumaquamarine' => '#66cdaa',
        'mediumblue' => '#0000cd',
        'mediumorchid' => '#ba55d3',
        'mediumpurple' => '#9370d8',
        'mediumseagreen' => '#3cb371',
        'mediumslateblue' => '#7b68ee',
        'mediumspringgreen' => '#00fa9a',
        'mediumturquoise' => '#48d1cc',
        'mediumvioletred' => '#c71585',
        'midnightblue' => '#191970',
        'mintcream' => '#f5fffa',
        'mistyrose' => '#ffe4e1',
        'moccasin' => '#ffe4b5',
        'navajowhite' => '#ffdead',
        'oldlace' => '#fdf5e6',
        'olivedrab' => '#6b8e23',
        'orangered' => '#ff4500',
        'orchid' => '#da70d6',
        'palegoldenrod' => '#eee8aa',
        'palegreen' => '#98fb98',
        'paleturquoise' => '#afeeee',
        'palevioletred' => '#d87093',
        'papayawhip' => '#ffefd5',
        'peachpuff' => '#ffdab9',
        'peru' => '#cd853f',
        'pink' => '#ffc0cb',
        'plum' => '#dda0dd',
        'powderblue' => '#b0e0e6',
        'rosybrown' => '#bc8f8f',
        'royalblue' => '#4169e1',
        'saddlebrown' => '#8b4513',
        'salmon' => '#fa8072',
        'sandybrown' => '#f4a460',
        'seagreen' => '#2e8b57',
        'seashell' => '#fff5ee',
        'sienna' => '#a0522d',
        'skyblue' => '#87ceeb',
        'slateblue' => '#6a5acd',
        'slategray' => '#708090',
        'snow' => '#fffafa',
        'springgreen' => '#00ff7f',
        'steelblue' => '#4682b4',
        'tan' => '#d2b48c',
        'thistle' => '#d8bfd8',
        'tomato' => '#ff6347',
        'turquoise' => '#40e0d0',
        'violet' => '#ee82ee',
        'violetred' => '#d02090',
        'wheat' => '#f5deb3',
        'whitesmoke' => '#f5f5f5',
        'yellowgreen' => '#9acd32'
    );

    public static $backgroundPropDefault = array(
        'background-image' => 'none',
        'background-size' => 'auto',
        'background-repeat' => 'repeat',
        'background-position' => '0 0',
        'background-attachment' => 'scroll',
        'background-clip' => 'border',
        'background-origin' => 'padding',
        'background-color' => 'transparent'
    );

    public static $fontPropDefault = array(
        'font-style' => 'normal',
        'font-variant' => 'normal',
        'font-weight' => 'normal',
        'font-size' => '',
        'line-height' => '',
        'font-family' => '',
    );

    /**
     * @param Logger $logger
     * @param Configuration $configuration
     */
    public function __construct(Logger $logger, Configuration $configuration)
    {
        $this->logger = $logger;
        $this->configuration = $configuration;
    }

    /**
     * Optimises $css after parsing
     * @param array $css
     */
    public function postparse(array &$css)
    {
        if ($this->configuration->getPreserveCss()) {
            return;
        }

        if ($this->configuration->getMergeSelectors() === Configuration::MERGE_SELECTORS) {
            foreach ($css as $medium => $value) {
                $this->mergeSelectors($css[$medium]);
            }
        }

        if ($this->configuration->getDiscardInvalidSelectors()) {
            foreach ($css as $medium => $value) {
                $this->discardInvalidSelectors($css[$medium]);
            }
        }

        if ($this->configuration->getOptimiseShorthands() > Configuration::NOTHING) {
            foreach ($css as $medium => $value) {
                foreach ($value as $selector => $foo) {
                    $css[$medium][$selector] = $this->mergeFourValueShorthands($css[$medium][$selector]);

                    if ($this->configuration->getOptimiseShorthands() < Configuration::FONT) {
                        continue;
                    }

                    $css[$medium][$selector] = $this->mergeFont($css[$medium][$selector]);

                    if ($this->configuration->getOptimiseShorthands() < Configuration::BACKGROUND) {
                        continue;
                    }

                    $css[$medium][$selector] = $this->mergeBackground($css[$medium][$selector]);

                    if (empty($css[$medium][$selector])) {
                        unset($css[$medium][$selector]);
                    }
                }
            }
        }
    }

    /**
     * Optimises values
     * @param string $property
     * @param string $value
     * @return string
     */
    public function value($property, $value)
    {
        // optimise shorthand properties
        if (isset(self::$shorthands[$property])) {
            if ($property === 'border-radius') {
                $temp = $this->borderRadiusShorthand($value);
            } else {
                $temp = $this->shorthand($value); // FIXME - move
            }
            if ($temp != $value) {
                $this->logger->log("Optimised shorthand notation ($property): Changed '$value' to '$temp'", Logger::INFORMATION);
            }
            $value = $temp;
        }

        if ($property === 'background-image' && $this->configuration->getCompressColors()) {
            $value = $this->optimizeGradients($value);
        }

        // Remove whitespace at ! important
        $tmp = $this->compressImportant($value);
        if ($value != $tmp) {
            $value = $tmp;
            $this->logger->log('Optimised !important', Logger::INFORMATION);
        }

        return $value;
    }

    /**
     * Optimize shorhands
     * @param Parsed $parsed
     * @param string $at
     * @param string $selector
     * @param string $property
     * @param string $value
     */
    public function shorthands(Parsed $parsed, $at, $selector, $property, $value)
    {
        if (!$this->configuration->getOptimiseShorthands() || $this->configuration->getPreserveCss()) {
            return;
        }

        if ($property === 'font' && $this->configuration->getOptimiseShorthands() > Configuration::COMMON) {
            $parsed->css[$at][$selector]['font'] = '';
            $parsed->mergeCssBlocks($at, $selector, $this->dissolveShortFont($value));
        } else if ($property === 'background' && $this->configuration->getOptimiseShorthands() > Configuration::FONT) {
            $parsed->css[$at][$selector]['background'] = '';
            $parsed->mergeCssBlocks($at, $selector, $this->dissolveShortBackground($value));
        } else if ($property === 'border-radius') {
            return;
        } else if (isset(self::$shorthands[$property])) {
            $parsed->mergeCssBlocks($at, $selector, $this->dissolveFourValueShorthands($property, $value));
            $parsed->css[$at][$selector][$property] = '';
        }
    }

    /**
     * Optimises a sub-value
     * @version 1.1
     * @param string $property
     * @param string $subValue
     * @return string
     */
    public function subValue($property, $subValue)
    {
        $subValue = trim($subValue);
        if ($subValue == '') { // caution : '0'
            return '';
        }

        $important = '';
        if (CSSTidy::isImportant($subValue)) {
            $important = '!important';
            $subValue = CSSTidy::removeImportant($subValue, false);
        }

        // Compress font-weight
        if ($property === 'font-weight' && $this->configuration->getCompressFontWeight()) {
            static $optimizedFontWeight = array('bold' => 700, 'normal' => 400);
            if (isset($optimizedFontWeight[$subValue])) {
                $optimized = $optimizedFontWeight[$subValue];
                $this->logger->log("Optimised font-weight: Changed '$subValue' to '$optimized'", Logger::INFORMATION);
                $subValue = $optimized;
            }
        }

        $temp = $this->compressNumbers($property, $subValue);

        if (strcasecmp($temp, $subValue) !== 0) {
            if (strlen($temp) > strlen($subValue)) {
                $this->logger->log("Fixed invalid number: Changed '{$subValue}' to '{$temp}'", Logger::WARNING);
            } else {
                $this->logger->log("Optimised number: Changed '{$subValue}' to '{$temp}'", Logger::INFORMATION);
            }
            $subValue = $temp;
        }

        if ($this->configuration->getCompressColors()) {
            $temp = $this->cutColor($subValue);
            if ($temp !== $subValue) {
                if (isset(self::$replaceColors[$subValue])) {
                    $this->logger->log("Fixed invalid color name: Changed '{$subValue}' to '{$temp}'", Logger::WARNING);
                } else {
                    $this->logger->log("Optimised color: Changed '{$subValue}' to '{$temp}'", Logger::INFORMATION);
                }
                $subValue = $temp;
            }
        }

        return $subValue . $important;
    }

    /**
     * Removes unnecessary whitespace in ! important
     * @param string $string
     * @return string
     * @access public
     * @version 1.1
     */
    public function compressImportant($string)
    {
        if (CSSTidy::isImportant($string)) {
            $string = CSSTidy::removeImportant($string, false) . '!important';
        }
        return $string;
    }

    /**
     * Optimize border-radius property
     *
     * @param string $value
     * @return string
     */
    protected function borderRadiusShorthand($value)
    {
        $parts = explode('/', $value);

        if (empty($parts)) { // / delimiter in string not found
            return $value;
        }

        if (isset($parts[2])) {
            return $value; // border-radius value can contains only two parts
        }

        foreach ($parts as &$part) {
            $part = $this->shorthand(trim($part));
        }

        return implode('/', $parts);
    }

    /**
     * Compresses shorthand values. Example: margin:1px 1px 1px 1px -> margin:1px
     * @param string $value
     * @return string
     * @version 1.0
     */
    protected function shorthand($value)
    {
        $important = '';
        if (CSSTidy::isImportant($value)) {
            $value = CSSTidy::removeImportant($value, false);
            $important = '!important';
        }

        $values = explode(' ', $value);
        switch (count($values)) {
            case 4:
                if ($values[0] == $values[1] && $values[0] == $values[2] && $values[0] == $values[3]) {
                    return $values[0] . $important;
                } elseif ($values[1] == $values[3] && $values[0] == $values[2]) {
                    return $values[0] . ' ' . $values[1] . $important;
                } elseif ($values[1] == $values[3]) {
                    return $values[0] . ' ' . $values[1] . ' ' . $values[2] . $important;
                }
                break;

            case 3:
                if ($values[0] == $values[1] && $values[0] == $values[2]) {
                    return $values[0] . $important;
                } elseif ($values[0] == $values[2]) {
                    return $values[0] . ' ' . $values[1] . $important;
                }
                break;

            case 2:
                if ($values[0] == $values[1]) {
                    return $values[0] . $important;
                }
                break;
        }

        return $value;
    }

    /**
     * Color compression function. Converts all rgb() values to #-values and uses the short-form if possible. Also replaces 4 color names by #-values.
     * @param string $color
     * @return string
     * @version 1.1
     */
    protected function cutColor($color) 
    {
        static $shorterNames = array(
            /* color name -> hex code */
            'black' => '#000',
            'fuchsia' => '#f0f',
            'white' => '#fff',
            'yellow' => '#ff0',

            /* hex code -> color name */
            '#800000' => 'maroon',
            '#ffa500' => 'orange',
            '#808000' => 'olive',
            '#800080' => 'purple',
            '#008000' => 'green',
            '#000080' => 'navy',
            '#008080' => 'teal',
            '#c0c0c0' => 'silver',
            '#808080' => 'gray',
            '#f00' => 'red',
        );

        // rgb(0,0,0) -> #000000 (or #000 in this case later)
        $type = strtolower(strstr($color, '(', true));

        if ($type === 'rgb' || $type === 'hsl' ) {
            $colorTmp = substr($color, 4, -1);
            $colorTmp = explode(',', $colorTmp);

            if (count($colorTmp) > 3) {
                $this->logger->log("RGB or HSL color value supports only three items", Logger::WARNING);
                $colorTmp = array_slice($colorTmp, 0, 3);
            } else if (count($colorTmp) !== 3) {
                $this->logger->log("RGB or HSL color value supports only three items", Logger::ERROR);
                return $color;
            }

            if ($type === 'rgb') {
                $color = $this->convertRgbToHex($colorTmp);
            } else {
                $color = $this->convertHslToHex($colorTmp);
            }
        } else if ($type === 'rgba' || $type === 'hsla') {
            $colorTmp = substr($color, 5, -1);
            $colorTmp = explode(',', $colorTmp);

            if (count($colorTmp) > 4) {
                $this->logger->log(strtoupper($type) . " color value supports only four items", Logger::WARNING);
                $colorTmp = array_slice($colorTmp, 0, 4);
            } else if (count($colorTmp) !== 4) {
                $this->logger->log(strtoupper($type) ." color value supports only four items", Logger::ERROR);
                return $color;
            }

            if ($colorTmp[3] == 1) { // no alpha is set -> convert to HEX
                $colorTmp = array_slice($colorTmp, 0, 3);
                $color = ($type === 'rgba' ? $this->convertRgbToHex($colorTmp) : $this->convertHslToHex($colorTmp));
            } else if ($colorTmp[3] == 0) { // full transparency
                $color = 'rgba(0,0,0,0)';
            } else {
                if ($type === 'hsla') {
                    $colorTmp[0] = $this->compressAngle($colorTmp[0]);
                }
                $color = "$type($colorTmp[0],$colorTmp[1],$colorTmp[2],{$this->compressNumber($colorTmp[3])})";
            }
        } else {
            // Fix bad color names
            if (isset(self::$replaceColors[strtolower($color)])) {
                $color = self::$replaceColors[strtolower($color)];
            }
        }

        if (strlen($color) === 7 && $color{0} === '#') {
            $color = strtolower($color); // Lower hex color for better gziping

            // #aabbcc -> #abc
            if ($color{1} === $color{2} && $color{3} === $color{4} && $color{5} === $color{6}) {
                $color = '#' . $color{1} . $color{3} . $color{5};
            }
        }

        if (isset($shorterNames[strtolower($color)])) {
            $color = $shorterNames[strtolower($color)];
        }

        return $color;
    }

    /**
     * @param array $parts
     * @return array
     */
    protected function convertRgbToHex(array $parts)
    {
        foreach ($parts as &$part) {
            $part = trim($part);

            if (substr($part, -1) === '%') {
                $part = round((255 * $part) / 100);
            }
        }

        return $this->threeByteArrayToHex($parts);
    }

    /**
     * Convert color from HSL to RGB
     * @param array $parts (H, S, L)
     * @return array (R, G, B)
     */
    protected function convertHslToHex(array $parts)
    {
        list ($h, $s, $l) = $parts;

        $h = ((($h % 360) + 360) % 360) / 360;

        $normalizeSOrL = function($value, $name) {
            if (!substr($value, -1) === '%') {
                $this->logger->log("HSL $name must be a percent value", Logger::WARNING);
            }

            if ((int) $value > 100) {
                $this->logger->log("HSL $name must be lower than 100%", Logger::WARNING);
            }

            return (int) $value / 100;
        };

        $s = $normalizeSOrL($s, 'saturation');
        $l = $normalizeSOrL($l, 'light');

        $m2 = ($l <= 0.5) ? $l * ($s + 1) : ($l + $s - $l * $s);
        $m1 = $l * 2 - $m2;

        $output = array();

        foreach (array($h + 1/3, $h, $h - 1/3) as $mH) {
            if ($mH < 0) {
                ++$mH;
            } else if ($mH > 1) {
                --$mH;
            }

            if ($mH * 6 < 1) {
                $output[] = $m1 + ($m2 - $m1) * $mH * 6;
            } else if ($mH * 2 < 1) {
                $output[] = $m2;
            } else if ($mH * 3 < 2) {
                $output[] = $m1 + ($m2 - $m1) * (2/3 - $mH) * 6;
            } else {
                $output[] = $m1;
            }
        }

        // Convert back to 1 -> 255
        foreach ($output as &$rgb) {
            $rgb = round($rgb * 255);
        }

        return $this->threeByteArrayToHex($output);
    }

    /**
     * @param array $array
     * @return string
     */
    protected function threeByteArrayToHex(array $array)
    {
        $hex = '#';

        foreach ($array as $byte) {
            if ($byte < 16) {
                if ($byte < 0) {
                    $byte = 0;
                }
                $hex .= '0' . dechex($byte);
            } else {
                if ($byte > 255) {
                    $byte = 255;
                }
                $hex .= dechex($byte);
            }
        }

        return $hex;
    }

    /**
     * Compresses numbers (ie. 1.0 becomes 1 or 1.100 becomes 1.1 )
     * @param string $property
     * @param string $subValue
     * @return string
     */
    protected function compressNumbers($property, $subValue)
    {
        // for font:1em/1em sans-serif...;
        if ($property === 'font') {
            $parts = explode('/', $subValue);
        } else {
            $parts = array($subValue);
        }

        foreach ($parts as &$part) {
            // if we are not dealing with a number at this point, do not optimise anything
            $number = $this->analyseCssNumber($part);
            if ($number === false) {
                return $subValue;
            }

            // Fix bad colors
            if (isset(self::$colorValues[$property])) {
                $part = '#' . $part;
                continue;
            }

            if (abs($number[0]) > 0) {
                if ($number[1] === '' && in_array($property, self::$unitValues, true)) {
                    $number[1] = 'px';
                }
            } else {
                $number[1] = '';
            }

            $part = $number[0] . $number[1];
        }

        return (isset($parts[1]) ? $parts[0] . '/' . $parts[1] : $parts[0]);
    }

    /**
     * Checks if a given string is a CSS valid number. If it is,
     * an array containing the value and unit is returned
     * @param string $string
     * @return array ('unit' if unit is found or '' if no unit exists, number value) or false if no number
     */
    protected function analyseCssNumber($string)
    {
        // most simple checks first
        if (!isset($string{0}) || $string{0} === '#' || ctype_alpha($string{0})) {
            return false;
        }

        $return = array(0, '');

        if ($string === '0') {
            return $return;
        }

        $return[0] = $this->compressNumber($string);

        /*preg_match('~([-]?([0-9]*\.[0-9]+|[0-9]+))(.*)~si', $string, $matches);

        if ($matches[1] === '') {
            return false;
        }

        $return[1] = trim($matches[3]);

        if ($return[1] !== '' && !in_array($return[1], self::$units)) {
            return false;
        }*/

        // TODO: Optimize
        // Look for unit and split from value if exists
        foreach (self::$units as $unit) {
            if (!($unitInString = stristr($string, $unit))) { // mb_strpos() fails with "false"
                continue;
            }
            $expectUnitAt = strlen($string) - strlen($unit);
            $actualPosition = strpos($string, $unitInString);
            if ($expectUnitAt === $actualPosition) {
                $return[1] = $unit;
                $string = substr($string, 0, - strlen($unit));
                break;
            }
        }

        if (!is_numeric($string)) {
            return false;
        }

        return $return;
    }

    /**
     * Removes 0 from decimal number between -1 - 1
     * Example: 0.3 -> .3; -0.3 -> -.3
     * @param string $string
     * @return string without any non numeric character
     */
    protected function compressNumber($string)
    {
        $float = floatval($string);
        if (abs($float) > 0 && abs($float) < 1) {
            if ($float < 0) {
                return '-' . ltrim(substr($float, 1), '0');
            } else {
                return ltrim($float, '0');
            }
        }

        return $float;
    }

    /**
     * @param int $angle
     * @return int
     */
    protected function compressAngle($angle)
    {
        $angle = (($angle % 360) + 360) % 360; // normalize from 0 to 359

        if ($angle > 350) {
            $angle -= 360;
        }

        return $angle;
    }

    /**
     * Merges selectors with same properties. Example: a{color:red} b{color:red} -> a,b{color:red}
     * Very basic and has at least one bug. Hopefully there is a replacement soon.
     * @param array $array
     */
    protected function mergeSelectors(array &$css)
    {
        foreach ($css as $key => $value) {
            if (!isset($css[$key])) {
                continue;
            }

            // Check if properties also exist in another selector
            $keys = array();
            // PHP bug (?) without $css = $array; here
            foreach ($css as $selector => $vali) {
                if ($selector == $key) {
                    continue;
                }

                if ($css[$key] === $vali) {
                    $keys[] = $selector;
                }
            }

            if (!empty($keys)) {
                $newSelector = $key;
                unset($css[$key]);

                foreach ($keys as $selector) {
                    unset($css[$selector]);
                    $newSelector .= ',' . $selector;
                }

                $css[$newSelector] = $value;
            }
        }
    }

    /**
     * Removes invalid selectors and their corresponding rule-sets as
     * defined by 4.1.7 in REC-CSS2. This is a very rudimentary check
     * and should be replaced by a full-blown parsing algorithm or
     * regular expression
     * @version 1.4
     * @param array $array
     */
    protected function discardInvalidSelectors(array &$array)
    {
        foreach ($array as $selector => $decls) {
            $ok = true;
            $selectors = array_map('trim', explode(',', $selector));

            foreach ($selectors as $s) {
                $simpleSelectors = preg_split('/\s*[+>~\s]\s*/', $s);
                foreach ($simpleSelectors as $ss) {
                    if ($ss === '') {
                        $ok = false;
                        break 2;
                    }
                    // could also check $ss for internal structure,
                    // but that probably would be too slow
                }
            }

            if (!$ok) {
                unset($array[$selector]);
            }
        }
    }

    /**
     * Dissolves properties like padding:10px 10px 10px to padding-top:10px;padding-bottom:10px;...
     * @param string $property
     * @param string $value
     * @return array
     * @version 1.0
     * @see merge_4value_shorthands()
     */
    protected function dissolveFourValueShorthands($property, $value)
    {
        $shorthands = self::$shorthands[$property];

        $important = '';
        if (CSSTidy::isImportant($value)) {
            $value = CSSTidy::removeImportant($value, false);
            $important = '!important';
        }

        $values = explode(' ', $value);

        $return = array();
        switch (count($values)) {
            case 4:
                for ($i = 0; $i < 4; $i++) {
                    $return[$shorthands[$i]] = $values[$i] . $important;
                }
                break;

            case 3:
                $return[$shorthands[0]] = $values[0] . $important;
                $return[$shorthands[1]] = $values[1] . $important;
                $return[$shorthands[3]] = $values[1] . $important;
                $return[$shorthands[2]] = $values[2] . $important;
                break;

            case 2:
                for ($i = 0; $i < 4; $i++) {
                    $return[$shorthands[$i]] = (($i % 2 != 0)) ? $values[1] . $important : $values[0] . $important;
                }
                break;

            default:
                for ($i = 0; $i < 4; $i++) {
                    $return[$shorthands[$i]] = $values[0] . $important;
                }
                break;
        }

        return $return;
    }

    /**
     * Merges Shorthand properties again, the opposite of dissolve_4value_shorthands()
     * @param array $array
     * @return array
     * @version 1.2
     */
    function mergeFourValueShorthands(array $array)
    {
        $return = $array;

        foreach (self::$shorthands as $key => $value) {
            if (isset($array[$value[0]]) && isset($array[$value[1]])
                            && isset($array[$value[2]]) && isset($array[$value[3]]) && $value !== 0) {
                $return[$key] = '';

                $important = '';
                for ($i = 0; $i < 4; $i++) {
                    $val = $array[$value[$i]];
                    if (CSSTidy::isImportant($val)) {
                        $important = '!important';
                        $return[$key] .= CSSTidy::removeImportant($val, false) . ' ';
                    } else {
                        $return[$key] .= $val . ' ';
                    }
                    unset($return[$value[$i]]);
                }
                $return[$key] = $this->shorthand(trim($return[$key] . $important));
            }
        }
        return $return;
    }

    /**
     * Dissolve background property
     * @param string $str_value
     * @return array
     * @todo full CSS 3 compliance
     */
    protected function dissolveShortBackground($str_value)
    {
        // don't try to explose background gradient !
        if (stripos($str_value, "gradient(") !== false) {
            return array('background' => $str_value);
        }
        
        static $repeat = array('repeat', 'repeat-x', 'repeat-y', 'no-repeat', 'space');
        static $attachment = array('scroll', 'fixed', 'local');
        static $clip = array('border', 'padding');
        static $origin = array('border', 'padding', 'content');
        static $pos = array('top', 'center', 'bottom', 'left', 'right');

        $important = '';
        $return = array('background-image' => null, 'background-size' => null, 'background-repeat' => null, 'background-position' => null, 'background-attachment' => null, 'background-clip' => null, 'background-origin' => null, 'background-color' => null);

        if (CSSTidy::isImportant($str_value)) {
            $important = ' !important';
            $str_value = CSSTidy::removeImportant($str_value, false);
        }

        $str_value = $this->explodeWs(',', $str_value);
        foreach ($str_value as $strVal) {
            $have = array(
                'clip' => false,
                'pos' => false,
                'color' => false,
                'bg' => false,
            );

            if (is_array($strVal)) {
                $strVal = $strVal[0];
            }

            $strVal = $this->explodeWs(' ', trim($strVal));

            foreach ($strVal as $current) {
                if ($have['bg'] === false && (substr($current, 0, 4) === 'url(' || $current === 'none')) {
                    $return['background-image'] .= $current . ',';
                    $have['bg'] = true;
                } elseif (in_array($current, $repeat, true)) {
                    $return['background-repeat'] .= $current . ',';
                } elseif (in_array($current, $attachment, true)) {
                    $return['background-attachment'] .= $current . ',';
                } elseif (in_array($current, $clip, true) && !$have['clip']) {
                    $return['background-clip'] .= $current . ',';
                    $have['clip'] = true;
                } elseif (in_array($current, $origin, true)) {
                    $return['background-origin'] .= $current . ',';
                } elseif ($current{0} === '(') {
                    $return['background-size'] .= substr($current, 1, -1) . ',';
                } elseif (in_array($current, $pos, true) || is_numeric($current{0}) || $current{0} === null || $current{0} === '-' || $current{0} === '.') {
                    $return['background-position'] .= $current . ($have['pos'] ? ',' : ' ');
                    $have['pos'] = true;
                } elseif (!$have['color']) {
                    $return['background-color'] .= $current . ',';
                    $have['color'] = true;
                }
            }
        }

        foreach (self::$backgroundPropDefault as $backgroundProperty => $defaultValue) {
            if ($return[$backgroundProperty] !== null) {
                $return[$backgroundProperty] = substr($return[$backgroundProperty], 0, -1) . $important;
            } else {
                $return[$backgroundProperty] = $defaultValue . $important;
            }
        }

        return $return;
    }

    /**
     * Merges all background properties
     * @param array $inputCss
     * @return array
     * @version 1.0
     * @see dissolve_short_bg()
     * @todo full CSS 3 compliance
     */
    protected function mergeBackground($inputCss)
    {
        // Max number of background images. CSS3 not yet fully implemented
        $numberOfValues = @max(count($this->explodeWs(',', $inputCss['background-image'])), count($this->explodeWs(',', $inputCss['background-color'])), 1);
        // Array with background images to check if BG image exists
        $bg_img_array = @$this->explodeWs(',', CSSTidy::removeImportant($inputCss['background-image']));
        $newBackgroundValue = '';
        $important = '';

        // if background properties is here and not empty, don't try anything
        if (isset($inputCss['background']) && $inputCss['background']) {
            return $inputCss;
        }
        
        for ($i = 0; $i < $numberOfValues; $i++) {
            foreach (self::$backgroundPropDefault as $bg_property => $defaultValue) {
                // Skip if property does not exist
                if (!isset($inputCss[$bg_property])) {
                    continue;
                }

                $currentValue = $inputCss[$bg_property];
                // skip all optimisation if gradient() somewhere
                if (stripos($currentValue, "gradient(") !== false) {
                    return $inputCss;
                }

                // Skip some properties if there is no background image
                if ((!isset($bg_img_array[$i]) || $bg_img_array[$i] === 'none')
                                && ($bg_property === 'background-size' || $bg_property === 'background-position'
                                || $bg_property === 'background-attachment' || $bg_property === 'background-repeat')) {
                    continue;
                }

                // Remove !important
                if (CSSTidy::isImportant($currentValue)) {
                    $important = ' !important';
                    $currentValue = CSSTidy::removeImportant($currentValue, false);
                }

                // Do not add default values
                if ($currentValue === $defaultValue) {
                    continue;
                }

                $temp = $this->explodeWs(',', $currentValue);

                if (isset($temp[$i])) {
                    if ($bg_property === 'background-size') {
                        $newBackgroundValue .= '(' . $temp[$i] . ') ';
                    } else {
                        $newBackgroundValue .= $temp[$i] . ' ';
                    }
                }
            }

            $newBackgroundValue = trim($newBackgroundValue);
            if ($i != $numberOfValues - 1) {
                $newBackgroundValue .= ',';
            }
        }

        // Delete all background-properties
        foreach (self::$backgroundPropDefault as $bg_property => $foo) {
            unset($inputCss[$bg_property]);
        }

        // Add new background property
        if ($newBackgroundValue !== '') {
            $inputCss['background'] = $newBackgroundValue . $important;
        } elseif (isset($inputCss['background'])) {
            $inputCss['background'] = 'none';
        }

        return $inputCss;
    }

    /**
     * Dissolve font property
     * @param string $value
     * @return array
     * @version 1.3
     * @see merge_font()
     */
    protected function dissolveShortFont($value)
    {
        static $font_weight = array('normal', 'bold', 'bolder', 'lighter', 100, 200, 300, 400, 500, 600, 700, 800, 900);
        static $font_variant = array('normal', 'small-caps');
        static $font_style = array('normal', 'italic', 'oblique');

        $important = '';
        $return = array('font-style' => null, 'font-variant' => null, 'font-weight' => null, 'font-size' => null, 'line-height' => null, 'font-family' => null);

        if (CSSTidy::isImportant($value)) {
            $important = '!important';
            $value = CSSTidy::removeImportant($value, false);
        }

        $have = array(
            'style' => false,
            'variant' => false,
            'weight' => false,
            'size' => false,
        );

        // Detects if font-family consists of several words w/o quotes
        $multiwords = false;

        // Workaround with multiple font-family
        $value = $this->explodeWs(',', trim($value));

        $value[0] = $this->explodeWs(' ', trim($value[0]));

        for ($j = 0; $j < count($value[0]); $j++) {
            if ($have['weight'] === false && in_array($value[0][$j], $font_weight)) {
                $return['font-weight'] = $value[0][$j];
                $have['weight'] = true;
            } elseif ($have['variant'] === false && in_array($value[0][$j], $font_variant)) {
                $return['font-variant'] = $value[0][$j];
                $have['variant'] = true;
            } elseif ($have['style'] === false && in_array($value[0][$j], $font_style)) {
                $return['font-style'] = $value[0][$j];
                $have['style'] = true;
            } elseif ($have['size'] === false && (is_numeric($value[0][$j]{0}) || $value[0][$j]{0} === null || $value[0][$j]{0} === '.')) {
                $size = $this->explodeWs('/', trim($value[0][$j]));
                $return['font-size'] = $size[0];
                if (isset($size[1])) {
                    $return['line-height'] = $size[1];
                } else {
                    $return['line-height'] = ''; // don't add 'normal' !
                }
                $have['size'] = true;
            } else {
                if (isset($return['font-family'])) {
                    $return['font-family'] .= ' ' . $value[0][$j];
                    $multiwords = true;
                } else {
                    $return['font-family'] = $value[0][$j];
                }
            }
        }
        // add quotes if we have several qords in font-family
        if ($multiwords !== false) {
            $return['font-family'] = '"' . $return['font-family'] . '"';
        }
        $i = 1;
        while (isset($value[$i])) {
            $return['font-family'] .= ',' . trim($value[$i]);
            $i++;
        }

        // Fix for 100 and more font-size
        if ($have['size'] === false && isset($return['font-weight']) &&
                        is_numeric($return['font-weight']{0})) {
            $return['font-size'] = $return['font-weight'];
            unset($return['font-weight']);
        }

        foreach (self::$fontPropDefault as $font_prop => $default_value) {
            if ($return[$font_prop] !== null) {
                $return[$font_prop] = $return[$font_prop] . $important;
            } else {
                $return[$font_prop] = $default_value . $important;
            }
        }
        return $return;
    }

    /**
     * Merges all fonts properties
     * @param array $inputCss
     * @return array
     * @version 1.3
     * @see dissolve_short_font()
     */
    protected function mergeFont($inputCss)
    {
        $new_font_value = '';
        $important = '';
        // Skip if not font-family and font-size set
        if (isset($inputCss['font-family']) && isset($inputCss['font-size'])) {
            // fix several words in font-family - add quotes
            if (isset($inputCss['font-family'])) {
                $families = explode(",", $inputCss['font-family']);
                $result_families = array();
                foreach ($families as $family) {
                    $family = trim($family);
                    $len = strlen($family);
                    if (strpos($family, " ") &&
                                    !(($family{0} == '"' && $family{$len - 1} == '"') ||
                                    ($family{0} == "'" && $family{$len - 1} == "'"))) {
                        $family = '"' . $family . '"';
                    }
                    $result_families[] = $family;
                }
                $inputCss['font-family'] = implode(",", $result_families);
            }

            foreach (self::$fontPropDefault as $fontProperty => $defaultValue) {

                // Skip if property does not exist
                if (!isset($inputCss[$fontProperty])) {
                    continue;
                }

                $currentValue = $inputCss[$fontProperty];

                // Skip if default value is used
                if ($currentValue === $defaultValue) {
                    continue;
                }

                // Remove !important
                if (CSSTidy::isImportant($currentValue)) {
                    $important = '!important';
                    $currentValue = CSSTidy::removeImportant($currentValue, false);
                }

                $new_font_value .= $currentValue;
                // Add delimiter
                $new_font_value .= ( $fontProperty === 'font-size' &&
                                isset($inputCss['line-height'])) ? '/' : ' ';
            }

            $new_font_value = trim($new_font_value);

            // Delete all font-properties
            foreach (self::$fontPropDefault as $fontProperty => $defaultValue) {
                if ($fontProperty !== 'font' || !$new_font_value)
                    unset($inputCss[$fontProperty]);
            }

            // Add new font property
            if ($new_font_value !== '') {
                $inputCss['font'] = $new_font_value . $important;
            }
        }

        return $inputCss;
    }

    /**
     * Compress color inside gradient definition
     * @param string $string
     * @return string
     */
    protected function optimizeGradients($string)
    {
        /*
         * Gradinet functions and color start from
         * -webkit-gradient syntax is not supported
         */
        static $supportedGradients = array(
            '-webkit-repeating-linear-gradient' => 1,
            '-moz-repeating-linear-gradient' => 1,
            '-o-repeating-linear-gradient' => 1,
            'repeating-linear-gradient' => 1,
            '-webkit-linear-gradient' => 1,
            '-moz-linear-gradient' => 1,
            '-o-linear-gradient' => 1,
            'linear-gradient' => 1,
            '-webkit-repeating-radial-gradient' => 2,
            '-moz-repeating-radial-gradient' => 2,
            '-o-repeating-radial-gradient' => 2,
            'repeating-radial-gradient' => 2,
            '-webkit-radial-gradient' => 2,
            '-moz-radial-gradient' => 2,
            '-o-radial-gradient' => 2,
            'radial-gradient' => 2,
        );

        $type = strstr($string, '(', true);

        if ($type === false || !isset($supportedGradients[$type])) {
            return $string; // value is not gradient or unsupported type
        }

        $string = substr($string, strlen($type) + 1, -1); // Remove linear-gradient()
        $parts = $this->explodeWs(',', $string);

        $start = $supportedGradients[$type];
        foreach ($parts as $i => &$part) {
            if ($i < $start) {
                continue;
            }

            $colorAndLength = $this->explodeWs(' ', $part);
            $colorAndLength[0] = $this->cutColor($colorAndLength[0]);
            $part = implode(' ', $colorAndLength);
        }

        return "$type(" . implode(',', $parts) . ')';
    }

     /**
     * Explodes a string as explode() does, however, not if $sep is escaped or within a string.
     * @param string $sep separator
     * @param string $string
     * @return array
     */
    protected function explodeWs($sep, $string)
    {
        if ($string === '' || $string === $sep) {
            return array();
        }

        $insideString = false;
        $to = '';
        $output = array(0 => '');
        $num = 0;

        for ($i = 0, $len = strlen($string); $i < $len; $i++) {
            if ($insideString) {
                if ($string{$i} === $to && !CSSTidy::escaped($string, $i)) {
                    $insideString = false;
                }
            } else {
                if ($string{$i} === $sep && !CSSTidy::escaped($string, $i)) {
                    ++$num;
                    $output[$num] = '';
                    continue;
                } else if ($string{$i} === '"' || $string{$i} === '\'' || $string{$i} === '(' && !CSSTidy::escaped($string, $i)) {
                    $insideString = true;
                    $to = ($string{$i} === '(') ? ')' : $string{$i};
                }
            }

            $output[$num] .= $string{$i};
        }

        return $output;
    }
}